/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Dr3wiz (https://sketchfab.com/Dr3wiz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/desktop-design-cute-51db0e25a29740d8abb4c648a5c7f012
Title: Desktop design cute
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useControls } from 'leva';



const HackerRoom = (props) => {
  // Leva controls for position (optional, can be used if you want to control position from here)
  const controls = useControls({
    positionX: { value: 0, min: -10, max: 10, step: 0.1 },
    positionY: { value: 0, min: -10, max: 10, step: 0.1 },
    positionZ: { value: 0, min: -10, max: 10, step: 0.1 },
  });
  const { nodes, materials } = useGLTF('/models/hacker-room.glb')
  return (
    <group {...props} dispose={null} onClick={props.onAssetClick}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.176}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.025}>
          <group position={[0.596, 29.289, 5.184]} rotation={[-Math.PI / 2, 0, 0]} scale={3.269}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Enter002_Material_#60_0'].geometry}
              material={materials.Material_60}
              position={[2.315, 0.973, -0.18]}
              scale={[1.969, 1.721, 0.89]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Espacio002_Material_#60_0'].geometry}
              material={materials.Material_60}
              position={[0.556, -0.698, -0.18]}
              scale={[1.497, 1.721, 0.89]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Tab002_Material_#60_0'].geometry}
              material={materials.Material_60}
              position={[-1.913, 0.048, -0.18]}
              scale={[1.721, 1.721, 0.89]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['tecl_019_Material_#62_0'].geometry}
              material={materials.Material_62}
              position={[-2.242, 0.746, -0.18]}
              scale={[1.721, 1.721, 0.89]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['tecl_020_Material_#61_0'].geometry}
              material={materials.Material_61}
              position={[-1.549, 0.746, -0.18]}
              scale={[1.721, 1.721, 0.89]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['tecl_021_Material_#61_0'].geometry}
              material={materials.Material_61}
              position={[-0.855, 0.746, -0.18]}
              scale={[1.721, 1.721, 0.89]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['tecl_022_Material_#61_0'].geometry}
              material={materials.Material_61}
              position={[-0.164, 0.746, -0.18]}
              scale={[1.721, 1.721, 0.89]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['tecl_023_Material_#62_0'].geometry}
              material={materials.Material_62}
              position={[-1.16, 0.041, -0.18]}
              scale={[1.721, 1.721, 0.89]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['tecl_024_Material_#62_0'].geometry}
              material={materials.Material_62}
              position={[-0.472, 0.041, -0.18]}
              scale={[1.721, 1.721, 0.89]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['tecl_025_Material_#61_0'].geometry}
              material={materials.Material_61}
              position={[0.513, 0.746, -0.18]}
              scale={[1.721, 1.721, 0.89]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['tecl_026_Material_#61_0'].geometry}
              material={materials.Material_61}
              position={[1.207, 0.746, -0.18]}
              scale={[1.721, 1.721, 0.89]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['tecl_027_Material_#62_0'].geometry}
              material={materials.Material_62}
              position={[0.226, 0.041, -0.18]}
              scale={[1.721, 1.721, 0.89]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['tecl_028_Material_#62_0'].geometry}
              material={materials.Material_62}
              position={[0.915, 0.041, -0.18]}
              scale={[1.721, 1.721, 0.89]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['tecl_029_Material_#62_0'].geometry}
              material={materials.Material_62}
              position={[-2.087, -0.692, -0.18]}
              scale={[2.424, 1.721, 0.89]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['tecl_030_Material_#62_0'].geometry}
              material={materials.Material_62}
              position={[1.903, -0.692, -0.18]}
              scale={[2.424, 1.721, 0.89]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['teclado002_Material_#59_0'].geometry}
              material={materials.Material_59}
              position={[0.209, -0.119, -0.292]}
              scale={[2.498, 1.721, 1.299]}
            />
          </group>
          <group
            position={[19.197, 28.813, 4.869]}
            rotation={[-Math.PI / 2, 0, -0.308]}
            scale={0.235}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Str001__0.geometry}
              material={materials.Str001__0}
              position={[0.276, -0.205, -3.086]}
            />
          </group>
          <group
            position={[19.953, 34.983, -7.555]}
            rotation={[0, 0, Math.PI / 6]}
            scale={[0.172, 0.173, 0.124]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Moon_Material_#86_0'].geometry}
              material={materials.Material_86}
              position={[14.8, 0.138, 0]}
            />
          </group>
          <group position={[0, 31.928, 0.052]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-0.441, 15.689, 21.798]} rotation={[Math.PI / 2, 0, 0]} scale={0.716}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes['Arc_Material_#75_0'].geometry}
                material={materials.Material_75}
                position={[-0.095, -50.065, 0]}
              />
            </group>
            <group position={[-0.093, 0.052, -4.913]} rotation={[0, 0, -Math.PI / 2]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes['Table_Material_#76_0'].geometry}
                material={materials.Material_76}
                position={[-0.193, 0, -27.015]}
              />
            </group>
            <group
              position={[-21.322, -1.679, -19.021]}
              rotation={[0, 0, -Math.PI / 2]}
              scale={[0.804, 0.698, 0.954]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes['Cajns01_Material_#72_0'].geometry}
                material={materials.Material_72}
                position={[-3.728, 0, -22.441]}
              />
            </group>
            <group
              position={[-21.322, -1.679, -27.656]}
              rotation={[0, 0, -Math.PI / 2]}
              scale={[0.804, 0.698, 0.954]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes['Cajns02_Material_#72_0'].geometry}
                material={materials.Material_72}
                position={[-3.728, 0, -22.441]}
              />
            </group>
            <group
              position={[-21.322, -1.679, -10.528]}
              rotation={[0, 0, -Math.PI / 2]}
              scale={[0.804, 0.698, 0.954]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes['Cajns00_Material_#72_0'].geometry}
                material={materials.Material_72}
                position={[-3.728, 0, -22.441]}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Pvt_Material_#65_0'].geometry}
              material={materials.Material_65}
              position={[22.388, 14.635, -3.476]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Cld_1_Material_#64_0'].geometry}
              material={materials.Material_64}
              position={[20.912, 14.035, 1.642]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.482}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Cld_2_Material_#64_0'].geometry}
              material={materials.Material_64}
              position={[20.912, 14.035, 22.748]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.482}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Rpsa_2_Material_#65_0'].geometry}
              material={materials.Material_65}
              position={[21.531, 8.784, 17.21]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Str_Material_#63_0'].geometry}
              material={materials.Material_63}
              position={[-23.544, 13.979, 22.698]}
              rotation={[Math.PI / 2, 0, -0.308]}
              scale={0.726}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Rpsa_Material_#65_0'].geometry}
              material={materials.Material_65}
              position={[-23.563, 8.978, 18.721]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Prlla02_Material_#80_0'].geometry}
              material={materials.Material_80}
              position={[-21.354, -13.75, -27.547]}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Prlla01_Material_#80_0'].geometry}
              material={materials.Material_80}
              position={[-21.354, -13.75, -19.109]}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Prlla00_Material_#80_0'].geometry}
              material={materials.Material_80}
              position={[-21.354, -13.75, -10.672]}
              rotation={[Math.PI / 2, 0, 0]}
            />
          </group>
          <group position={[0, 17.6, 28.801]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Sprteslla02__0.geometry}
              material={materials.Str001__0}
              position={[4.352, 0.368, -12.907]}
              rotation={[Math.PI / 2, 0, -0.175]}
              scale={[-0.523, 0.523, 0.523]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Cjnes01_Material_#64_0'].geometry}
              material={materials.Material_64}
              position={[0.077, -8.974, 10.8]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[0.733, 1.067, 1.198]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Sllatbo__0.geometry}
              material={materials.Str001__0}
              position={[0, 0.021, -11.491]}
              rotation={[0, 0, -Math.PI]}
              scale={1.198}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Rda01_Material_#80_0'].geometry}
              material={materials.Material_80}
              position={[9.857, 0.871, -16.332]}
              rotation={[Math.PI / 2, 0, Math.PI / 2]}
              scale={[-1.198, 1.198, 1.198]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Sprteslla01__0.geometry}
              material={materials.Str001__0}
              position={[0.343, 4.442, -12.907]}
              rotation={[1.396, -Math.PI / 2, 0]}
              scale={0.523}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Cjnes00_Material_#64_0'].geometry}
              material={materials.Material_64}
              position={[0.077, 1.698, -2.714]}
              rotation={[0, 0, -Math.PI]}
              scale={[0.733, 1.067, 1.198]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Rda00_Material_#80_0'].geometry}
              material={materials.Material_80}
              position={[0.846, -9.947, -16.332]}
              rotation={[0, -Math.PI / 2, 0]}
              scale={[-1.198, 1.198, 1.198]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Sprteslla03__0.geometry}
              material={materials.Str001__0}
              position={[-4.352, 0.368, -12.907]}
              rotation={[Math.PI / 2, 0, 0.175]}
              scale={0.523}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Rda03_Material_#80_0'].geometry}
              material={materials.Material_80}
              position={[0.846, 9.947, -16.332]}
              rotation={[Math.PI, -Math.PI / 2, 0]}
              scale={1.198}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Sprteslla00__0.geometry}
              material={materials.Str001__0}
              position={[0.343, -4.442, -12.907]}
              rotation={[1.745, -Math.PI / 2, 0]}
              scale={[-0.523, 0.523, 0.523]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Rda02_Material_#80_0'].geometry}
              material={materials.Material_80}
              position={[-9.857, 0.871, -16.332]}
              rotation={[Math.PI / 2, 0, -Math.PI / 2]}
              scale={1.198}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Sllsprte_Material_#66_0'].geometry}
              material={materials.Material_66}
              position={[0.073, -7.043, -3.401]}
              rotation={[0, 0, -Math.PI]}
              scale={[0.353, 1.016, 1.067]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Psmno00_Material_#80_0'].geometry}
              material={materials.Material_80}
              position={[6.792, -1.164, 1.64]}
              rotation={[Math.PI / 2, Math.PI / 2, 0]}
              scale={0.508}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Psmno01_Material_#80_0'].geometry}
              material={materials.Material_80}
              position={[-6.792, -1.164, 1.64]}
              rotation={[Math.PI / 2, Math.PI / 2, 0]}
              scale={0.508}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Dj2_Material_#77_0'].geometry}
            material={materials.Material_77}
            position={[-16.054, 28.374, 6.898]}
            rotation={[-Math.PI / 2, 0, -0.087]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Monitir_Material_#79_0'].geometry}
            material={materials.Material_79}
            position={[0.801, 31.62, -5.859]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={3.269}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Mnbook_Material_#84_0'].geometry}
            material={materials.Material_84}
            position={[14.197, 49.666, -8.867]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Mnjrron_Material_#64_0'].geometry}
            material={materials.Material_64}
            position={[-23.543, 51.166, -8.882]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.852}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Time_Material_#78_0'].geometry}
            material={materials.Material_78}
            position={[20.693, 28.247, -7.555]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Mnbook001_Material_#87_0'].geometry}
            material={materials.Material_87}
            position={[16.204, 49.666, -8.867]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Mnbook002_Material_#84_0'].geometry}
            material={materials.Material_84}
            position={[19.417, 52.678, -8.867]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Mnbook003_Material_#87_0'].geometry}
            material={materials.Material_87}
            position={[19.417, 50.693, -8.867]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Petal05_Material_#67_0'].geometry}
            material={materials.Material_67}
            position={[-25.292, 54.638, -8.948]}
            rotation={[0, Math.PI / 2, 0]}
            scale={0.24}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Petal04_Material_#67_0'].geometry}
            material={materials.Material_67}
            position={[-23.386, 54.638, -10.829]}
            scale={0.24}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Petal03_Material_#67_0'].geometry}
            material={materials.Material_67}
            position={[-21.722, 54.638, -8.948]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={[-0.24, 0.24, 0.24]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Petal02_Material_#67_0'].geometry}
            material={materials.Material_67}
            position={[-23.462, 54.638, -6.882]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={0.24}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Petal00_Material_#67_0'].geometry}
            material={materials.Material_67}
            position={[-24.088, 56.247, -9.66]}
            rotation={[0, Math.PI / 4, 0]}
            scale={0.24}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Petal01_Material_#67_0'].geometry}
            material={materials.Material_67}
            position={[-22.764, 56.247, -8.281]}
            rotation={[-Math.PI, -Math.PI / 4, -Math.PI]}
            scale={0.24}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Mnjrron001_Material_#88_0'].geometry}
            material={materials.Material_88}
            position={[-23.543, 51.677, -8.882]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.852}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Cld_alfm_Material_#58_0'].geometry}
            material={materials.Material_58}
            position={[20.854, 28.38, 5.415]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.371}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Cryla00_Material_#68_0'].geometry}
            material={materials.Material_68}
            position={[-17.073, 28.717, 0.047]}
            rotation={[Math.PI, -0.087, Math.PI / 2]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Cjclr_Material_#83_0'].geometry}
            material={materials.Material_83}
            position={[-22.39, 28.367, -6.501]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Cryla01_Material_#81_0'].geometry}
            material={materials.Material_81}
            position={[-15.979, 28.717, 5.303]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Cryla02_Material_#82_0'].geometry}
            material={materials.Material_82}
            position={[-23.044, 28.603, -6.199]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Cryla03_Material_#71_0'].geometry}
            material={materials.Material_71}
            position={[-27.92, 28.717, 8.01]}
            rotation={[0, -Math.PI / 9, -Math.PI / 2]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Cryla04_Material_#70_0'].geometry}
            material={materials.Material_70}
            position={[-20.418, 28.603, -6.196]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Cryla05_Material_#69_0'].geometry}
            material={materials.Material_69}
            position={[-12.487, 28.717, -2.072]}
            rotation={[0, -0.611, -Math.PI / 2]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Cjclrtp_Material_#73_0'].geometry}
            material={materials.Material_73}
            position={[-15.406, 29.752, -6.583]}
            rotation={[1.598, -0.151, 0.177]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Djo1_Material_#74_0'].geometry}
            material={materials.Material_74}
            position={[-21.956, 28.38, 1.718]}
            rotation={[-Math.PI / 2, 0, Math.PI / 9]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rud__0.geometry}
            material={materials.Str001__0}
            position={[19.371, 28.838, 3.45]}
            rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
          />
        </group>
      </group>
    </group>
  )
}
useGLTF.preload('/models/hacker-room.glb')
export default HackerRoom;